{% set version = "5.2.0" %}

package:
  name: nbformat
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbformat/nbformat-{{ version }}.tar.gz
  sha256: 93df0b9c67221d38fb970c48f6d361819a6c388299a0ef3171bbb912edfe1324

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ipython_genutils
    - traitlets >=4.1
    - jsonschema >=2.4,!=2.5.0
    - jupyter_core

test:
  source_files:
    - tests
  commands:
    - pip check
    - jupyter trust --version
    - jupyter-trust --help
    - pytest -vv --cov nbformat --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 79
  requires:
    - pip
    - pytest
    - pytest-cov
    - python-fastjsonschema
    - testpath
  imports:
    - nbformat

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  summary: The Jupyter Notebook format
  license_file: COPYING.md
  doc_url: https://nbformat.readthedocs.io
  dev_url: https://github.com/jupyter/nbformat

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer
    - bollwyvl
