{% set version = "5.1.2" %}

package:
  name: nbformat
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbformat/nbformat-{{ version }}.tar.gz
  sha256: 1d223e64a18bfa7cdf2db2e9ba8a818312fc2a0701d2e910b58df66809385a56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - ipython_genutils
    - traitlets >=4.1
    - jsonschema >=2.4,!=2.5.0
    - jupyter_core

test:
  commands:
    - pip check
    - jupyter-trust -h
  requires:
    - pip
  imports:
    - nbformat

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  summary: The Jupyter Notebook format
  license_file: COPYING.md

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer
