{% set version = "5.1.2" %}
# TODO: investigate upstream (whether it is expected these should exist)
{% set k_skips = ["upgrade_v4_to_4_dot_5", "sample_notebook"] %}
# TODO: determine whether this is OS-specific (happens)
{% set cov_min = 70 %}

package:
  name: nbformat
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbformat/nbformat-{{ version }}.tar.gz
  sha256: 1d223e64a18bfa7cdf2db2e9ba8a818312fc2a0701d2e910b58df66809385a56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - ipython_genutils
    - traitlets >=4.1
    - jsonschema >=2.4,!=2.5.0
    - jupyter_core

test:
  commands:
    - pip check
    - jupyter-trust -h
    - pytest -vv --pyargs nbformat --cov nbformat --no-cov-on-fail --cov-fail-under={{ cov_min }} -k "not ({{ ' or '.join(k_skips) }})"
  requires:
    - pip
    - pytest
    - pytest-cov
    - python-fastjsonschema
    - testpath
  imports:
    - nbformat

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  summary: The Jupyter Notebook format
  license_file: COPYING.md
  docs_url: https://nbformat.readthedocs.io
  dev_url: https://github.com/jupyter/nbformat

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer
    - bollwyvl
